### ISSUE TITLE
VS2019環境のpythonに対応

### ISSUE THREAD

**Issue by alphaizm** [alphaizm/UploadWeight2Fitbit#1]
token.batをVS2019で実行できるように対応する

**Comment by alphaizm** [comment]
SSDを変更しWin10を再インストールしてbatを実行した結果
以下のエラーが表示された。

```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\cherrypy\_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\cherrypy\_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\cherrypy\lib\encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Users\xxx\OneDrive\ドキュメント\Visual Studio 2019\Project\PythonFitbit\python-fitbit\gather_keys_oauth2.py", line 50, in index
    self.fitbit.client.fetch_access_token(code)
  File "C:\Users\xxx\OneDrive\ドキュメント\Visual Studio 2019\Project\PythonFitbit\python-fitbit\fitbit\api.py", line 146, in fetch_access_token
    code=code)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\requests_oauthlib\oauth2_session.py", line 307, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 438, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\oauthlib\oauth2\rfc6749\errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientError: (invalid_client) 
```

**Comment by alphaizm** [comment]
ググった結果、同様の問題に突き当たっている人を発見
[fitbit community](https://community.fitbit.com/t5/Web-API-Development/Invalid-Client-Error/td-p/3290376)

解決コメント

> Apparently it's a common problem, it can often be solved by downgrading the libraries
> requests-oauthlib==1.1.0
> and
> oauthlib==2.1.0.
> There is more discussion on the python fitbit api github here: https://github.com/orcasgit/python-fitbit/issues/142.

⇒ python-fitbitを更新することでエラーが表示されなくなった

**Comment by alphaizm** [comment]
Visual Studio 2019上からF5実行した場合
以下のエラー発生
![image](https://user-images.githubusercontent.com/46560526/65150990-2bea4600-da60-11e9-9837-5aace1a65d91.png)

直接スクリプトを実行した場合、無事実行できることを確認
`python.exe "ディレクトリ¥PythonFitbit.py"`
